-- Re-enable RLS on all tables
-- Created: 2024-12-23

-- Enable RLS on all tables
ALTER TABLE characters ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE abilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE traits ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE quests ENABLE ROW LEVEL SECURITY;
ALTER TABLE main_quest_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_rolls ENABLE ROW LEVEL SECURITY;
ALTER TABLE hit_dice ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE action_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE inspiration_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_effects ENABLE ROW LEVEL SECURITY;
